
# SEO settings
title: "Alxndrr"
title2: "" # default: ""
description: ""
keywords: "Alxndrr, series, televisie, films, games, tech"
url: http://alexvanderweij.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: 
disqus_shortname: "hnbloggithub"
twitter_username: "Alxndrr"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Alex van der Weij"
  job      : "Seriekoning"
  bio      : "Bio"
  thumb    : /images/author.jpg
  email    : Alexvanderweij@gmail.com
  url      : http://alxndrr.xyz
  github   : http://www.alexvanderweij.nl
  twitter  : http://twitter.com/Alxndrr
  facebook : https://www.facebook.com/Alexvanderweij

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@Alxndrr"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : Over mij
    title: Over mij
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
